spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shoppingmall?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Wkrwjs4602!
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: desc
    operationSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
      path: /api-docs
      show-actuator: true
      default-consumes-media-type: application/json
      default-produces-media-type: application/json
      paths-to-match:
        - /**
server:
  tomcat:
    max-http-header-size: 8192